// @ts-check
import js from '@eslint/js';
import globals from 'globals';
import reactHooks from 'eslint-plugin-react-hooks';
import reactRefresh from 'eslint-plugin-react-refresh';
import tseslint from 'typescript-eslint';
import prettier from 'eslint-config-prettier';

export default tseslint.config(
  /**
   * shadcn/ui components are vendored, not authored here — they are generated
   * and re-generated by the CLI, so linting them means fighting a tool.
   *
   * They are listed one by one rather than ignoring `src/shared/ui/**`, because
   * that directory now holds more first-party code than vendored code
   * (`form-sheet`, `responsive-dialog`, `value-row`, `section`, the four field
   * components…) and a blanket ignore left all of it unlinted. Listing the
   * vendored files makes "linted" the default for anything new.
   */
  {
    ignores: [
      'dist/**',
      'dev-dist/**',
      'node_modules/**',
      'coverage/**',
      'src/shared/ui/alert-dialog.tsx',
      'src/shared/ui/alert.tsx',
      'src/shared/ui/avatar.tsx',
      'src/shared/ui/badge.tsx',
      'src/shared/ui/button.tsx',
      'src/shared/ui/calendar.tsx',
      'src/shared/ui/card.tsx',
      'src/shared/ui/checkbox.tsx',
      'src/shared/ui/dialog.tsx',
      'src/shared/ui/drawer.tsx',
      'src/shared/ui/dropdown-menu.tsx',
      'src/shared/ui/form.tsx',
      'src/shared/ui/input.tsx',
      'src/shared/ui/label.tsx',
      'src/shared/ui/popover.tsx',
      'src/shared/ui/progress.tsx',
      'src/shared/ui/radio-group.tsx',
      'src/shared/ui/scroll-area.tsx',
      'src/shared/ui/select.tsx',
      'src/shared/ui/separator.tsx',
      'src/shared/ui/sheet.tsx',
      'src/shared/ui/skeleton.tsx',
      'src/shared/ui/sonner.tsx',
      'src/shared/ui/switch.tsx',
      'src/shared/ui/tabs.tsx',
      'src/shared/ui/textarea.tsx',
      'src/shared/ui/tooltip.tsx',
    ],
  },
  js.configs.recommended,
  ...tseslint.configs.recommended,
  {
    files: ['**/*.{ts,tsx}'],
    languageOptions: {
      ecmaVersion: 2023,
      globals: { ...globals.browser, ...globals.serviceworker },
    },
    plugins: {
      'react-hooks': reactHooks,
      'react-refresh': reactRefresh,
    },
    rules: {
      ...reactHooks.configs.recommended.rules,
      'react-refresh/only-export-components': ['warn', { allowConstantExport: true }],
      '@typescript-eslint/no-unused-vars': [
        'error',
        { argsIgnorePattern: '^_', varsIgnorePattern: '^_' },
      ],
      '@typescript-eslint/consistent-type-imports': [
        'error',
        { prefer: 'type-imports', fixStyle: 'inline-type-imports' },
      ],
      'no-console': ['warn', { allow: ['warn', 'error'] }],
    },
  },
  prettier,
);
