import { createBrowserRouter, type RouteObject } from 'react-router-dom';
import { ROUTES } from '@/shared/lib/routes';
import {
  RedirectIfAuthenticated,
  RequireAuth,
  RequirePermission,
} from '@/shared/auth/require-auth';
import { LoadingScreen } from '@/shared/components/LoadingScreen';
import { AppShell, AuthShell } from './layout/AppShell';
import { RootLayout } from './RootLayout';
import { NotFound, RouteErrorBoundary } from './ErrorBoundary';

/**
 * ============================================================================
 *                            THE ROUTE CONTRACT
 * ============================================================================
 *
 * Other agents plug feature screens into the table below. This list is the
 * agreement between the shell and every feature module — do not invent new
 * top-level paths without updating `docs/architecture/frontend.md` and
 * `src/shared/lib/routes.ts` in the same change.
 *
 * | Path                     | Owner module        | Guard                    |
 * |--------------------------|---------------------|--------------------------|
 * | `/`                      | features/today      | auth                     |
 * | `/tasks`                 | features/tasks      | auth + `task:read`       |
 * | `/calendar`              | features/calendar   | auth + `event:read`      |
 * | `/goals`                 | features/goals      | auth + `goal:read`       |
 * | `/shopping`              | features/shopping   | auth + `shopping:read`   |
 * | `/wall`                  | features/wall       | auth                     |
 * | `/family`                | features/family     | auth + `member:read`     |
 * | `/settings`              | features/settings   | auth                     |
 * | `/settings/profile`      | features/settings   | auth                     |
 * | `/settings/notifications`| features/settings   | auth + `notification:manage:own` |
 * | `/settings/accounts`     | features/settings   | auth + `identity:manage:own`     |
 * | `/admin/members`         | features/admin      | auth + `member:approve`  |
 * | `/login`                 | features/auth       | public (redirects if signed in) |
 * | `/auth/pending`          | features/auth       | public                   |
 * | `/auth/rejected`         | features/auth       | public                   |
 * | `/auth/suspended`        | features/auth       | public                   |
 * | anything else            | —                   | 404                      |
 *
 * ### Rules for feature agents
 *
 * 1. **Do not edit this file to add sub-routes inside your own feature.** Add a
 *    nested `<Routes>`/`<Outlet>` inside your page, or ask the shell owner to
 *    add a child entry here. Detail views are *paths under your section*
 *    (`/tasks/:taskId`), never new top-level segments.
 * 2. Every page module **default-exports** a component that takes no props.
 * 3. Pages are lazy: the import lives here, so nothing in your feature is in
 *    the initial bundle.
 * 4. Guards are declarative and permission based (D4) — never `role ===`.
 *    `RequirePermission` takes the *base* permission; `own`/`any` is resolved
 *    by `useCan()`.
 * 5. Your page renders **inside** `AppShell`: no app bar, no navigation, no
 *    outer padding of your own. Start with `<PageHeader>`.
 *
 * `createBrowserRouter` (a data router) is required: `AppShell` uses
 * `useNavigation()` for the pending-navigation state, and the `lazy` route
 * property below is a data-router API.
 */

/** Helper: a lazily-loaded page module with a default export. */
function page(load: () => Promise<{ default: React.ComponentType }>) {
  return async (): Promise<{ Component: React.ComponentType }> => ({
    Component: (await load()).default,
  });
}

/** Helper: a lazily-loaded page exported under a name. */
function namedPage<K extends string>(load: () => Promise<Record<K, React.ComponentType>>, key: K) {
  return async (): Promise<{ Component: React.ComponentType }> => ({
    Component: (await load())[key],
  });
}

const authenticatedRoutes: RouteObject[] = [
  {
    index: true,
    lazy: page(() => import('@/features/today/pages/TodayPage')),
  },
  {
    path: ROUTES.tasks,
    element: <RequirePermission perm="task:read" />,
    children: [{ index: true, lazy: page(() => import('@/features/tasks/pages/TasksPage')) }],
  },
  {
    path: ROUTES.calendar,
    element: <RequirePermission perm="event:read" />,
    children: [{ index: true, lazy: page(() => import('@/features/calendar/pages/CalendarPage')) }],
  },
  {
    path: ROUTES.goals,
    element: <RequirePermission perm="goal:read" />,
    children: [{ index: true, lazy: page(() => import('@/features/goals/pages/GoalsPage')) }],
  },
  {
    path: ROUTES.shopping,
    element: <RequirePermission perm="shopping:read" />,
    children: [{ index: true, lazy: page(() => import('@/features/shopping/pages/ShoppingPage')) }],
  },
  {
    path: ROUTES.wall,
    lazy: page(() => import('@/features/wall/pages/WallPage')),
  },
  {
    path: ROUTES.family,
    element: <RequirePermission perm="member:read" />,
    children: [{ index: true, lazy: page(() => import('@/features/family/pages/FamilyPage')) }],
  },

  // ---- settings ----------------------------------------------------------
  {
    path: ROUTES.settings,
    lazy: page(() => import('@/features/settings/pages/SettingsPage')),
  },
  {
    path: ROUTES.settingsProfile,
    lazy: page(() => import('@/features/settings/pages/ProfilePage')),
  },
  {
    path: ROUTES.settingsNotifications,
    element: <RequirePermission perm="notification:manage:own" />,
    children: [
      { index: true, lazy: page(() => import('@/features/settings/pages/NotificationsPage')) },
    ],
  },
  {
    path: ROUTES.settingsAccounts,
    element: <RequirePermission perm="identity:manage:own" />,
    children: [{ index: true, lazy: page(() => import('@/features/settings/pages/AccountsPage')) }],
  },

  // ---- administration ----------------------------------------------------
  {
    path: ROUTES.adminMembers,
    element: <RequirePermission perm="member:approve" />,
    children: [{ index: true, lazy: page(() => import('@/features/admin/pages/MembersPage')) }],
  },
];

const topLevelRoutes: RouteObject[] = [
  // Public auth screens. `/auth/*` must render with no session at all (D3):
  // a `pending_approval` user is never issued one.
  {
    element: <AuthShell />,
    errorElement: <RouteErrorBoundary />,
    children: [
      {
        path: ROUTES.login,
        element: <RedirectIfAuthenticated />,
        children: [{ index: true, lazy: page(() => import('@/features/auth/pages/LoginPage')) }],
      },
      {
        path: ROUTES.authPending,
        lazy: namedPage(
          () => import('@/features/auth/pages/AccountStatusPages'),
          'PendingApprovalPage',
        ),
      },
      {
        path: ROUTES.authRejected,
        lazy: namedPage(() => import('@/features/auth/pages/AccountStatusPages'), 'RejectedPage'),
      },
      {
        path: ROUTES.authSuspended,
        lazy: namedPage(() => import('@/features/auth/pages/AccountStatusPages'), 'SuspendedPage'),
      },
    ],
  },

  // Everything else lives behind a session and inside the app chrome.
  {
    element: <RequireAuth />,
    errorElement: <RouteErrorBoundary />,
    children: [
      {
        element: <AppShell />,
        children: authenticatedRoutes,
      },
    ],
  },

  { path: '*', element: <NotFound /> },
];

/** `RootLayout` wraps everything so the API layer gets a client-side `navigate`. */
export const routes: RouteObject[] = [
  {
    element: <RootLayout />,
    errorElement: <RouteErrorBoundary />,
    // The initial route is always `lazy`, so the data router needs something to
    // render while the first chunk loads.
    hydrateFallbackElement: <LoadingScreen fullscreen />,
    children: topLevelRoutes,
  },
];

export function createAppRouter() {
  return createBrowserRouter(routes);
}
