process.env.NODE_ENV = 'test';
process.env.TZ = 'Europe/Moscow';
process.env.DATABASE_URL ??= 'postgres://family:family@localhost:5432/family_test';
process.env.REDIS_URL ??= 'redis://localhost:6379/1';
process.env.APP_PUBLIC_URL ??= 'http://localhost:5173';
const S = 'test-secret-value-that-is-definitely-long-enough-000000';
process.env.JWT_ACCESS_SECRET ??= S;
process.env.JWT_REFRESH_SECRET ??= S;
process.env.COOKIE_SECRET ??= S;
process.env.ENCRYPTION_KEY ??= S;
process.env.ENABLE_WORKERS ??= 'false';
process.env.ENABLE_SWAGGER ??= 'false';
process.env.LOG_LEVEL ??= 'fatal';

import { installTemporal } from '../src/core/temporal.js';
await installTemporal();
const { buildApp } = await import('../src/app.js');
const { default: eventsRoutes } = await import('../src/modules/events/events.routes.js');
const app = await buildApp();
await app.register(eventsRoutes, { prefix: '/api' });
await app.ready();
const r = await app.inject({ method: 'GET', url: '/api/events/feed.ics?token=obviously-not-a-real-token' });
console.log(r.statusCode, r.payload);
await app.close();
process.exit(0);
