import { useState } from 'react';
import type { EventOccurrenceResponse, EditScope, PublicUser, Rsvp } from '@family/shared';
import { Cake, CalendarClock, Info, MapPin, Pencil, Repeat, Trash2 } from 'lucide-react';
import { Sheet, SheetContent, SheetDescription, SheetHeader, SheetTitle } from '@/shared/ui/sheet';
import { Button } from '@/shared/ui/button';
import { Badge } from '@/shared/ui/badge';
import { Separator } from '@/shared/ui/separator';
import { UserAvatar } from '@/shared/components/UserAvatar';
import { ConfirmDialog } from '@/shared/components/ConfirmDialog';
import { useCan } from '@/shared/auth/use-can';
import { formatDateLong, formatTimeRange } from '@/shared/lib/format';
import { cn } from '@/shared/lib/utils';
import { COMMON } from '@/shared/lib/i18n';
import { birthdayAge, occurrenceColor } from '../calendar-model';
import { useDeleteEvent, useEventSeries, useSetRsvp } from '../hooks';
import { CALENDAR_RU } from '../locale';
import { EditScopeDialog } from './EditScopeDialog';

const RSVP_CHOICES: { value: Rsvp; label: string }[] = [
  { value: 'yes', label: CALENDAR_RU.rsvpYes },
  { value: 'maybe', label: CALENDAR_RU.rsvpMaybe },
  { value: 'no', label: CALENDAR_RU.rsvpNo },
];

/**
 * The instance detail. Opened from the grid or the agenda.
 *
 * Birthdays (`sourceKind: 'user_birthday'`) are generated from a profile and
 * regenerated by a job, so they render with the age and an explanation instead
 * of edit and delete buttons — editing one here would be silently undone
 * (scheduling §6).
 */
export function EventDetailSheet(props: {
  occurrence: EventOccurrenceResponse | null;
  open: boolean;
  onOpenChange: (open: boolean) => void;
  members: Map<string, PublicUser>;
  birthdayAnchors: Map<string, string>;
  timeZone: string;
  onEdit: (occurrence: EventOccurrenceResponse) => void;
}) {
  const { occurrence } = props;
  const { can, userId } = useCan();
  const seriesQuery = useEventSeries(occurrence?.seriesId);
  const series = seriesQuery.data;
  const rsvp = useSetRsvp();
  const remove = useDeleteEvent(occurrence?.seriesId ?? '');

  const [scopeOpen, setScopeOpen] = useState(false);
  const [confirmOpen, setConfirmOpen] = useState(false);

  if (!occurrence) return null;

  const isGenerated = occurrence.sourceKind !== 'manual';
  const isBirthday = occurrence.sourceKind === 'user_birthday';
  const anchor = props.birthdayAnchors.get(occurrence.seriesId);
  const age = isBirthday && anchor ? birthdayAge(occurrence.occurrenceKey, anchor) : null;
  const recurring = Boolean(series?.recurrence.rrule);
  const color = occurrenceColor(occurrence);

  const canEdit = !isGenerated && can('event:update', series ?? null);
  const canDelete = !isGenerated && can('event:delete', series ?? null);
  const isAttendee = occurrence.attendees.some((attendee) => attendee.userId === userId);

  const doDelete = (scope: EditScope): void => {
    remove.mutate(
      { scope, ...(scope === 'all' ? {} : { occurrenceId: occurrence.id }) },
      {
        onSuccess: () => {
          setScopeOpen(false);
          setConfirmOpen(false);
          props.onOpenChange(false);
        },
      },
    );
  };

  return (
    <>
      <Sheet open={props.open} onOpenChange={props.onOpenChange}>
        <SheetContent
          side="bottom"
          data-scroll-pane
          data-testid="event-detail"
          className="max-h-[88dvh] overflow-y-auto rounded-t-2xl pb-safe sm:mx-auto sm:max-w-lg"
        >
          <SheetHeader className="gap-1">
            <span
              className="h-1.5 w-12 rounded-full"
              style={{ backgroundColor: color }}
              aria-hidden
            />
            <SheetTitle className="flex items-center gap-2 text-lg">
              {isBirthday ? <Cake className="size-4 shrink-0" aria-hidden /> : null}
              <span className="min-w-0 break-words">{occurrence.title}</span>
            </SheetTitle>
            <SheetDescription className="text-sm">
              {formatDateLong(occurrence.startsAt, props.timeZone)}
              {occurrence.isAllDay
                ? ` · ${CALENDAR_RU.allDay}`
                : ` · ${formatTimeRange(occurrence.startsAt, occurrence.endsAt, props.timeZone)}`}
            </SheetDescription>
          </SheetHeader>

          <div className="space-y-4 px-4 pb-4">
            <div className="flex flex-wrap gap-1.5">
              {isBirthday ? <Badge variant="secondary">{CALENDAR_RU.birthday}</Badge> : null}
              {age !== null ? (
                <Badge variant="outline" data-testid="birthday-age">
                  {CALENDAR_RU.age(age)}
                </Badge>
              ) : null}
              {occurrence.isException ? (
                <Badge variant="outline">{CALENDAR_RU.changedThisTime}</Badge>
              ) : null}
              {occurrence.status === 'cancelled' ? (
                <Badge variant="destructive">{CALENDAR_RU.cancelled}</Badge>
              ) : null}
              {occurrence.category ? (
                <Badge variant="ghost" className="border-border">
                  {occurrence.category}
                </Badge>
              ) : null}
            </div>

            {occurrence.location ? (
              <p className="flex items-start gap-2 text-sm text-foreground">
                <MapPin className="mt-0.5 size-4 shrink-0 text-muted-foreground" aria-hidden />
                <span className="min-w-0 break-words">{occurrence.location}</span>
              </p>
            ) : null}

            {occurrence.description ? (
              <p className="text-sm whitespace-pre-wrap text-muted-foreground">
                {occurrence.description}
              </p>
            ) : null}

            <p className="flex items-start gap-2 text-sm text-muted-foreground">
              <Repeat className="mt-0.5 size-4 shrink-0" aria-hidden />
              <span>{series ? series.recurrence.summary : CALENDAR_RU.noRepeat}</span>
            </p>

            {series && series.reminderOffsets.length > 0 ? (
              <p className="flex items-start gap-2 text-sm text-muted-foreground">
                <CalendarClock className="mt-0.5 size-4 shrink-0" aria-hidden />
                <span>
                  {series.reminderOffsets
                    .map(
                      (minutes) =>
                        CALENDAR_RU.reminderOptions.find((option) => option.minutes === minutes)
                          ?.label ?? `${String(minutes)} мин`,
                    )
                    .join(', ')}
                </span>
              </p>
            ) : null}

            <Separator />

            {/* ---- attendees ------------------------------------------- */}
            <div className="space-y-2">
              <h3 className="text-sm font-medium text-foreground">{CALENDAR_RU.attendees}</h3>
              {occurrence.attendees.length === 0 ? (
                <p className="text-sm text-muted-foreground">{CALENDAR_RU.noAttendees}</p>
              ) : (
                <ul className="space-y-1.5">
                  {occurrence.attendees.map((attendee) => {
                    const member = props.members.get(attendee.userId);
                    return (
                      <li key={attendee.userId} className="flex items-center gap-2">
                        <UserAvatar
                          user={{
                            id: attendee.userId,
                            displayName: member?.displayName ?? '—',
                            avatarUrl: member?.avatarUrl,
                          }}
                          size="sm"
                          highlighted={attendee.userId === userId}
                        />
                        <span className="min-w-0 flex-1 truncate text-sm">
                          {member?.displayName ?? '—'}
                        </span>
                        <Badge
                          variant={attendee.rsvp === 'yes' ? 'secondary' : 'outline'}
                          className={cn(attendee.rsvp === 'no' && 'opacity-60')}
                        >
                          {RSVP_LABEL[attendee.rsvp]}
                        </Badge>
                      </li>
                    );
                  })}
                </ul>
              )}
            </div>

            {/* ---- my answer -------------------------------------------- */}
            {isAttendee && !isGenerated ? (
              <div className="space-y-2">
                <h3 className="text-sm font-medium text-foreground">{CALENDAR_RU.rsvpQuestion}</h3>
                <div className="flex gap-2">
                  {RSVP_CHOICES.map((choice) => (
                    <Button
                      key={choice.value}
                      type="button"
                      variant={occurrence.myRsvp === choice.value ? 'default' : 'outline'}
                      className="h-11 flex-1"
                      disabled={rsvp.isPending}
                      onClick={() => {
                        rsvp.mutate({
                          occurrenceId: occurrence.id,
                          rsvp: choice.value,
                          applyToFuture: false,
                        });
                      }}
                    >
                      {choice.label}
                    </Button>
                  ))}
                </div>
              </div>
            ) : null}

            {/* ---- actions ---------------------------------------------- */}
            {isGenerated ? (
              <p className="flex items-start gap-2 rounded-xl bg-muted/60 p-3 text-sm text-muted-foreground">
                <Info className="mt-0.5 size-4 shrink-0" aria-hidden />
                <span>{isBirthday ? CALENDAR_RU.birthdayHint : CALENDAR_RU.seriesReadOnly}</span>
              </p>
            ) : (
              <div className="flex flex-wrap gap-2">
                {canEdit ? (
                  <Button
                    variant="outline"
                    className="h-11 flex-1"
                    onClick={() => {
                      props.onEdit(occurrence);
                    }}
                  >
                    <Pencil aria-hidden />
                    {COMMON.edit}
                  </Button>
                ) : null}
                {canDelete ? (
                  <Button
                    variant="outline"
                    className="h-11 flex-1 text-destructive"
                    disabled={remove.isPending}
                    onClick={() => {
                      if (recurring) setScopeOpen(true);
                      else setConfirmOpen(true);
                    }}
                  >
                    <Trash2 aria-hidden />
                    {COMMON.delete}
                  </Button>
                ) : null}
              </div>
            )}
          </div>
        </SheetContent>
      </Sheet>

      <EditScopeDialog
        open={scopeOpen}
        onOpenChange={setScopeOpen}
        mode="delete"
        isPending={remove.isPending}
        onConfirm={doDelete}
      />

      <ConfirmDialog
        open={confirmOpen}
        onOpenChange={setConfirmOpen}
        title={CALENDAR_RU.deleteConfirmTitle}
        description={CALENDAR_RU.deleteConfirmDescription}
        isPending={remove.isPending}
        onConfirm={() => {
          doDelete('all');
        }}
      />
    </>
  );
}

const RSVP_LABEL: Record<Rsvp, string> = {
  yes: CALENDAR_RU.rsvpYes,
  no: CALENDAR_RU.rsvpNo,
  maybe: CALENDAR_RU.rsvpMaybe,
  pending: CALENDAR_RU.rsvpPending,
};
